### ISSUE TITLE
Feature request: add support for Auto-Renewal Checkbox Add-On

### ISSUE THREAD

**Issue by MaryOJob** [strangerstudios/pmpro-payment-plans#53]
Is your feature request related to a problem?
Currently, the auto-renewal checkbox would only show up for the default plan. A customer (ticket 501547) wants the auto-renewals checkbox shown on all payment plans.

Describe the solution you'd like
Add support for Auto-Renewal Checkbox Add-On

**Comment by ipokkel** [comment]
This feature was requested in support: #532807

**Comment by MaryOJob** [comment]
Another request: #586419 (Moderators Only)

**Comment by kimcoleman** [comment]
The issue here is that the Auto-Renewal Checkbox Add On needs to be updated to get the level at checkout 

https://github.com/strangerstudios/pmpro-auto-renewal-checkbox/issues/25.

Once the issue in ARC is resolved, this issue will be resolved.

There are API calls that can be used to get the correct price and ARC can reflect that price in the labels shown to optionally choose automatic renewal.
