### ISSUE TITLE
Alternate payment plans do not appear in level descriptions

### ISSUE THREAD

**Issue by avianinvasion** [strangerstudios/pmpro-payment-plans#70]
While the alternate payment plans appear in the checkout options just fine, they do NOT appear alongside the standard price when selecting Levels or on the Checkout page. I've had to manually add that there's an annual subscription option in my Levels' descriptions, but that makes it show up in odd places where that description is displayed elsewhere.

It would be great if the add-on could change the various "The price for membership is $X per Month." blocks to list ALL the options provided by alternate payment plans. Thanks!

**Comment by kimcoleman** [comment]
There are many, many ways that people would want to display their payment plan options on a "pricing" table. For now, we are going to work to resolve issue #62 so that sites can build dynamic level checkout links with a plan "pre-selected".

Then, people can use custom gists OR build their pricing table with their page builder of choice and add any detail that they want to that page + links to each plan's checkout page.

The [pmpro_levels] shortcode is not required to use on your Membership Levels page. You can remove this shortcode or block and build the page however you want.
